name: Update requirements.txt

on:
  push:
    branches:
      - '*'  # Runs on pushes to any branch
    paths:
      - '**/*.py'  # Triggers the action on changes to Python files anywhere in your repository

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Update requirements.txt
      run: |
        pip freeze > requirements.txt

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add requirements.txt
        git commit -m "Update requirements.txt" -m "Automated update of requirements.txt via GitHub Actions." || echo "No changes to commit"
        git push
